import MinecraftTheme from '../../themes/minecraft';
import type CubeInfo from './cube.info';

export const left_cubes: Array<CubeInfo> = [
    { id: 0, x: 0, y: 0, z_index: 0, sprites: MinecraftTheme.block_textures.pieces[0] },
    { id: 1, x: 1, y: 0, z_index: 1, sprites: MinecraftTheme.block_textures.pieces[1] },
    { id: 2, x: 2, y: 0, z_index: 2, sprites: MinecraftTheme.block_textures.pieces[2] },
    { id: 3, x: 3, y: 0, z_index: 3, sprites: MinecraftTheme.block_textures.pieces[3] },
    { id: 4, x: 4, y: 0, z_index: 4, sprites: MinecraftTheme.block_textures.pieces[4] },
    { id: 5, x: 5, y: 0, z_index: 5, sprites: MinecraftTheme.block_textures.pieces[1] },
    { id: 6, x: 6, y: 0, z_index: 6, sprites: MinecraftTheme.block_textures.pieces[3] },

    { id: 50, x: 0, y: 1, z_index: 0, sprites: MinecraftTheme.block_textures.pieces[0] },
    { id: 51, x: 1, y: 1, z_index: 1, sprites: MinecraftTheme.block_textures.pieces[1] },
    { id: 52, x: 2, y: 1, z_index: 2, sprites: MinecraftTheme.block_textures.pieces[2] },
    { id: 53, x: 3, y: 1, z_index: 3, sprites: MinecraftTheme.block_textures.pieces[3] },
    { id: 54, x: 4, y: 1, z_index: 4, sprites: MinecraftTheme.block_textures.pieces[4] },
    { id: 55, x: 5, y: 1, z_index: 5, sprites: MinecraftTheme.block_textures.pieces[5] },
    { id: 56, x: 6, y: 1, z_index: 6, sprites: MinecraftTheme.block_textures.pieces[6] },

    // { id: 60, x: 0, y: 2, z_index: 0, sprites: MinecraftTheme.block_textures.pieces[0] },
    // { id: 61, x: 1, y: 2, z_index: 1, sprites: MinecraftTheme.block_textures.pieces[1] },
    // { id: 62, x: 2, y: 2, z_index: 2, sprites: MinecraftTheme.block_textures.pieces[2] },
    // { id: 63, x: 3, y: 2, z_index: 3, sprites: MinecraftTheme.block_textures.pieces[3] },
    // { id: 64, x: 4, y: 2, z_index: 4, sprites: MinecraftTheme.block_textures.pieces[4] },
    // { id: 65, x: 5, y: 2, z_index: 5, sprites: MinecraftTheme.block_textures.pieces[1] },
    // { id: 66, x: 6, y: 2, z_index: 6, sprites: MinecraftTheme.block_textures.pieces[3] },

    { id: 70, x: 0, y: 3, z_index: 0, sprites: MinecraftTheme.block_textures.pieces[0] },
    { id: 71, x: 1, y: 3, z_index: 1, sprites: MinecraftTheme.block_textures.pieces[1] },
    { id: 72, x: 2, y: 3, z_index: 2, sprites: MinecraftTheme.block_textures.pieces[2] },
    { id: 73, x: 3, y: 3, z_index: 3, sprites: MinecraftTheme.block_textures.pieces[3] },
    { id: 74, x: 4, y: 3, z_index: 4, sprites: MinecraftTheme.block_textures.pieces[4] },
    { id: 75, x: 5, y: 3, z_index: 5, sprites: MinecraftTheme.block_textures.pieces[5] },
    { id: 76, x: 6, y: 3, z_index: 6, sprites: MinecraftTheme.block_textures.pieces[6] },

    { id: 80, x: 0, y: 4, z_index: 0, sprites: MinecraftTheme.block_textures.pieces[0] },
    { id: 81, x: 1, y: 4, z_index: 1, sprites: MinecraftTheme.block_textures.pieces[1] },
    { id: 82, x: 2, y: 4, z_index: 2, sprites: MinecraftTheme.block_textures.pieces[2] },
    { id: 83, x: 3, y: 4, z_index: 3, sprites: MinecraftTheme.block_textures.pieces[3] },
    { id: 84, x: 4, y: 4, z_index: 4, sprites: MinecraftTheme.block_textures.pieces[4] },
    { id: 85, x: 5, y: 4, z_index: 5, sprites: MinecraftTheme.block_textures.pieces[5] },
    { id: 86, x: 6, y: 4, z_index: 6, sprites: MinecraftTheme.block_textures.pieces[6] },

    { id: 90, x: 0, y: 5, z_index: 0, sprites: MinecraftTheme.block_textures.pieces[0] },
    { id: 91, x: 1, y: 5, z_index: 1, sprites: MinecraftTheme.block_textures.pieces[1] },
    { id: 92, x: 2, y: 5, z_index: 2, sprites: MinecraftTheme.block_textures.pieces[2] },
    { id: 93, x: 3, y: 5, z_index: 3, sprites: MinecraftTheme.block_textures.pieces[3] },
    { id: 94, x: 4, y: 5, z_index: 4, sprites: MinecraftTheme.block_textures.pieces[4] },
    { id: 95, x: 5, y: 5, z_index: 5, sprites: MinecraftTheme.block_textures.pieces[5] },
    { id: 96, x: 6, y: 5, z_index: 6, sprites: MinecraftTheme.block_textures.pieces[6] },

    { id: 900, x: 0, y: 6, z_index: 0, sprites: MinecraftTheme.block_textures.pieces[0] },
    { id: 901, x: 1, y: 6, z_index: 1, sprites: MinecraftTheme.block_textures.pieces[1] },
    { id: 902, x: 2, y: 6, z_index: 2, sprites: MinecraftTheme.block_textures.pieces[2] },
    { id: 903, x: 3, y: 6, z_index: 3, sprites: MinecraftTheme.block_textures.pieces[3] },
    { id: 904, x: 4, y: 6, z_index: 4, sprites: MinecraftTheme.block_textures.pieces[4] },
    { id: 905, x: 5, y: 6, z_index: 5, sprites: MinecraftTheme.block_textures.pieces[5] },
    { id: 906, x: 6, y: 6, z_index: 6, sprites: MinecraftTheme.block_textures.pieces[6] },
    
    { id: 1900, x: 0, y: 7, z_index: 0, sprites: MinecraftTheme.block_textures.pieces[0] },
    { id: 1901, x: 1, y: 7, z_index: 1, sprites: MinecraftTheme.block_textures.pieces[1] },
    { id: 1902, x: 2, y: 7, z_index: 2, sprites: MinecraftTheme.block_textures.pieces[2] },
    { id: 1903, x: 3, y: 7, z_index: 3, sprites: MinecraftTheme.block_textures.pieces[3] },
    { id: 1904, x: 4, y: 7, z_index: 4, sprites: MinecraftTheme.block_textures.pieces[4] },
    { id: 1905, x: 5, y: 7, z_index: 5, sprites: MinecraftTheme.block_textures.pieces[5] },
    { id: 1906, x: 6, y: 7, z_index: 6, sprites: MinecraftTheme.block_textures.pieces[6] },

    // { id: 2900, x: 0, y: 8, z_index: 0, sprites: MinecraftTheme.block_textures.pieces[0] },
    // { id: 2901, x: 1, y: 8, z_index: 1, sprites: MinecraftTheme.block_textures.pieces[1] },
    // { id: 2902, x: 2, y: 8, z_index: 2, sprites: MinecraftTheme.block_textures.pieces[2] },
    // { id: 2903, x: 3, y: 8, z_index: 3, sprites: MinecraftTheme.block_textures.pieces[3] },
    // { id: 2904, x: 4, y: 8, z_index: 4, sprites: MinecraftTheme.block_textures.pieces[4] },
    // { id: 2905, x: 5, y: 8, z_index: 5, sprites: MinecraftTheme.block_textures.pieces[5] },
    // { id: 2906, x: 6, y: 8, z_index: 6, sprites: MinecraftTheme.block_textures.pieces[6] },

    { id: 3900, x: 0, y: 9, z_index: 0, sprites: MinecraftTheme.block_textures.pieces[0] },
    { id: 3901, x: 1, y: 9, z_index: 1, sprites: MinecraftTheme.block_textures.pieces[1] },
    { id: 3902, x: 2, y: 9, z_index: 2, sprites: MinecraftTheme.block_textures.pieces[2] },
    { id: 3903, x: 3, y: 9, z_index: 3, sprites: MinecraftTheme.block_textures.pieces[3] },
    { id: 3904, x: 4, y: 9, z_index: 4, sprites: MinecraftTheme.block_textures.pieces[4] },
    { id: 3905, x: 5, y: 9, z_index: 5, sprites: MinecraftTheme.block_textures.pieces[5] },
    { id: 3906, x: 6, y: 9, z_index: 6, sprites: MinecraftTheme.block_textures.pieces[6] },

    { id: 4900, x: 0, y: 10, z_index: 0, sprites: MinecraftTheme.block_textures.pieces[0] },
    { id: 4901, x: 1, y: 10, z_index: 1, sprites: MinecraftTheme.block_textures.pieces[1] },
    { id: 4902, x: 2, y: 10, z_index: 2, sprites: MinecraftTheme.block_textures.pieces[2] },
    { id: 4903, x: 3, y: 10, z_index: 3, sprites: MinecraftTheme.block_textures.pieces[3] },
    { id: 4904, x: 4, y: 10, z_index: 4, sprites: MinecraftTheme.block_textures.pieces[4] },
    { id: 4905, x: 5, y: 10, z_index: 5, sprites: MinecraftTheme.block_textures.pieces[5] },
    { id: 4906, x: 6, y: 10, z_index: 6, sprites: MinecraftTheme.block_textures.pieces[6] },

    { id: 5900, x: 0, y: 11, z_index: 0, sprites: MinecraftTheme.block_textures.pieces[0] },
    { id: 5901, x: 1, y: 11, z_index: 1, sprites: MinecraftTheme.block_textures.pieces[1] },
    { id: 5902, x: 2, y: 11, z_index: 2, sprites: MinecraftTheme.block_textures.pieces[2] },
    { id: 5903, x: 3, y: 11, z_index: 3, sprites: MinecraftTheme.block_textures.pieces[3] },
    { id: 5904, x: 4, y: 11, z_index: 4, sprites: MinecraftTheme.block_textures.pieces[4] },
    { id: 5905, x: 5, y: 11, z_index: 5, sprites: MinecraftTheme.block_textures.pieces[5] },
    { id: 5906, x: 6, y: 11, z_index: 6, sprites: MinecraftTheme.block_textures.pieces[6] },

    // { id: 15900, x: 0, y: 12, z_index: 0, sprites: MinecraftTheme.block_textures.pieces[0] },
    // { id: 15901, x: 1, y: 12, z_index: 1, sprites: MinecraftTheme.block_textures.pieces[1] },
    // { id: 15902, x: 2, y: 12, z_index: 2, sprites: MinecraftTheme.block_textures.pieces[2] },
    // { id: 15903, x: 3, y: 12, z_index: 3, sprites: MinecraftTheme.block_textures.pieces[3] },
    // { id: 15904, x: 4, y: 12, z_index: 4, sprites: MinecraftTheme.block_textures.pieces[4] },
    // { id: 15905, x: 5, y: 12, z_index: 5, sprites: MinecraftTheme.block_textures.pieces[1] },
    // { id: 15906, x: 6, y: 12, z_index: 6, sprites: MinecraftTheme.block_textures.pieces[3] },

    { id: 25900, x: 0, y: 13, z_index: 0, sprites: MinecraftTheme.block_textures.pieces[0] },
    { id: 25901, x: 1, y: 13, z_index: 1, sprites: MinecraftTheme.block_textures.pieces[1] },
    { id: 25902, x: 2, y: 13, z_index: 2, sprites: MinecraftTheme.block_textures.pieces[2] },
    { id: 25903, x: 3, y: 13, z_index: 3, sprites: MinecraftTheme.block_textures.pieces[3] },
    { id: 25904, x: 4, y: 13, z_index: 4, sprites: MinecraftTheme.block_textures.pieces[4] },
    { id: 25905, x: 5, y: 13, z_index: 5, sprites: MinecraftTheme.block_textures.pieces[5] },
    { id: 25906, x: 6, y: 13, z_index: 6, sprites: MinecraftTheme.block_textures.pieces[6] },

    { id: 35900, x: 0, y: 14, z_index: 0, sprites: MinecraftTheme.block_textures.pieces[0] },
    { id: 35901, x: 1, y: 14, z_index: 1, sprites: MinecraftTheme.block_textures.pieces[1] },
    { id: 35902, x: 2, y: 14, z_index: 2, sprites: MinecraftTheme.block_textures.pieces[2] },
    { id: 35903, x: 3, y: 14, z_index: 3, sprites: MinecraftTheme.block_textures.pieces[3] },
    { id: 35904, x: 4, y: 14, z_index: 4, sprites: MinecraftTheme.block_textures.pieces[4] },
    { id: 35905, x: 5, y: 14, z_index: 5, sprites: MinecraftTheme.block_textures.pieces[5] },
    { id: 35906, x: 6, y: 14, z_index: 6, sprites: MinecraftTheme.block_textures.pieces[6] },

    { id: 55900, x: 0, y: 15, z_index: 0, sprites: MinecraftTheme.block_textures.pieces[0] },
    { id: 55901, x: 1, y: 15, z_index: 1, sprites: MinecraftTheme.block_textures.pieces[1] },
    { id: 55902, x: 2, y: 15, z_index: 2, sprites: MinecraftTheme.block_textures.pieces[2] },
    { id: 55903, x: 3, y: 15, z_index: 3, sprites: MinecraftTheme.block_textures.pieces[3] },
    { id: 55904, x: 4, y: 15, z_index: 4, sprites: MinecraftTheme.block_textures.pieces[4] },
    { id: 55905, x: 5, y: 15, z_index: 5, sprites: MinecraftTheme.block_textures.pieces[5] },
    { id: 55906, x: 6, y: 15, z_index: 6, sprites: MinecraftTheme.block_textures.pieces[6] },

    { id: 65900, x: 0, y: 16, z_index: 0, sprites: MinecraftTheme.block_textures.pieces[0] },
    { id: 65901, x: 1, y: 16, z_index: 1, sprites: MinecraftTheme.block_textures.pieces[1] },
    { id: 65902, x: 2, y: 16, z_index: 2, sprites: MinecraftTheme.block_textures.pieces[2] },
    { id: 65903, x: 3, y: 16, z_index: 3, sprites: MinecraftTheme.block_textures.pieces[3] },
    { id: 65904, x: 4, y: 16, z_index: 4, sprites: MinecraftTheme.block_textures.pieces[4] },
    { id: 65905, x: 5, y: 16, z_index: 5, sprites: MinecraftTheme.block_textures.pieces[5] },
    { id: 65906, x: 6, y: 16, z_index: 6, sprites: MinecraftTheme.block_textures.pieces[6] },
];

export 	const right_cubes: Array<CubeInfo> = [
    {id: 30, x: 0, y: 0, z_index: 0, sprites: MinecraftTheme.block_textures.pieces[0] },
    {id: 31, x: 1, y: 0, z_index: 1, sprites: MinecraftTheme.block_textures.pieces[1] },
    {id: 32, x: 2, y: 0, z_index: 2, sprites: MinecraftTheme.block_textures.pieces[2] },
    {id: 33, x: 3, y: 0, z_index: 3, sprites: MinecraftTheme.block_textures.pieces[3] },
    {id: 34, x: 4, y: 0, z_index: 4, sprites: MinecraftTheme.block_textures.pieces[4] },
    {id: 35, x: 5, y: 0, z_index: 5, sprites: MinecraftTheme.block_textures.pieces[5] },
    {id: 36, x: 6, y: 0, z_index: 6, sprites: MinecraftTheme.block_textures.pieces[6] },
    {id: 37, x: 7, y: 0, z_index: 6, sprites: MinecraftTheme.block_textures.pieces[6] },
    {id: 38, x: 8, y: 0, z_index: 6, sprites: MinecraftTheme.block_textures.pieces[6] },
    {id: 39, x: 9, y: 0, z_index: 6, sprites: MinecraftTheme.block_textures.pieces[6] },
];